export const sampleJobs = [
  {
    title: "Junior Backend Developer",
    company: "Tech Solutions Inc.",
    description: "Looking for a Junior Backend Developer with Node.js and Express experience. You'll be building REST APIs and working with MongoDB. Must have good understanding of JavaScript and asynchronous programming.",
    location: "Manila, Philippines",
    experienceLevel: "Junior",
    employmentType: "Full-time",
    skills: ["Node.js", "Express.js", "MongoDB", "REST API", "JavaScript"],
    salary: { min: 30000, max: 50000, currency: "PHP" },
  },
  {
    title: "Full Stack Developer",
    company: "Digital Innovations",
    description: "Seeking a Full Stack Developer proficient in MERN stack. Will work on e-commerce platforms and real-time applications. React frontend with Node.js backend.",
    location: "Remote",
    experienceLevel: "Mid-Level",
    employmentType: "Remote",
    skills: ["React.js", "Node.js", "Express.js", "MongoDB", "JavaScript", "HTML5", "CSS3"],
    salary: { min: 50000, max: 80000, currency: "PHP" },
  },
  {
    title: "Frontend React Developer",
    company: "Creative Web Studio",
    description: "Looking for a Frontend Developer with strong React.js skills. Must have experience with responsive design, API integration, and modern frontend tools.",
    location: "Cebu, Philippines",
    experienceLevel: "Junior",
    employmentType: "Full-time",
    skills: ["React.js", "JavaScript", "HTML5", "CSS3", "Bootstrap", "REST API"],
    salary: { min: 35000, max: 55000, currency: "PHP" },
  },
  {
    title: "DevOps Engineer",
    company: "Cloud Solutions Co.",
    description: "Seeking DevOps Engineer with AWS experience. Will manage cloud infrastructure, CI/CD pipelines, and deployment automation.",
    location: "Remote",
    experienceLevel: "Senior",
    employmentType: "Remote",
    skills: ["AWS", "Docker", "Kubernetes", "CI/CD", "Linux", "Python"],
    salary: { min: 80000, max: 120000, currency: "PHP" },
  },
  {
    title: "Software Engineer (Java)",
    company: "Enterprise Systems",
    description: "Looking for Java developer with Spring Boot experience. Will work on enterprise applications and microservices architecture.",
    location: "Makati, Philippines",
    experienceLevel: "Mid-Level",
    employmentType: "Full-time",
    skills: ["Java", "Spring Boot", "MySQL", "REST API", "Git"],
    salary: { min: 60000, max: 90000, currency: "PHP" },
  },
];